### ISSUE TITLE
Did you use the autofluorescence unmixing  in training phase?

### ISSUE THREAD

**Issue by TardisBlue2** [BIIFSweden/MariaUlvmar2020-1#1]
If so, where can I see it in the code?

**Comment by cavenel** [comment]
Hi,

We did not perform unmixing and did therefore not remove the autofluorescence. So we didn't use autofluorescence unmixing in training phase.
Training of HEV-finder was done on 3 fluorescent channels: CCL21, Claudin-5 and peripheral node addressin.
